feat: supports extends in array format
qmhc/vite-plugin-dts pull request #202
Opened 2023-04-14 14:55 UTC by DreamOfIce

TypeScript5 starts to support multiple extends at the same time

Close #200

2023-04-14 15:30 UTC, qmhc requested changes

2023-04-14 15:30 UTC, qmhc commented on src/utils.ts
> +import type { CompilerOptions, Project } from 'ts-morph'
普通 `import` 和 `import type` 之间我们添加一个换行。

2023-04-14 15:30 UTC, qmhc commented on src/utils.ts
> +export function getTsConfig(tsConfigPath: string, project: Project) {
我觉得第二个参数改为传入一个读取方法 `readFile`，能够降低这个方法的耦合性。

2023-04-14 15:30 UTC, qmhc commented on src/utils.ts
> +    const extendsConfigs = tsConfig.extends instanceof Array ? tsConfig.extends : [tsConfig.extends]
此处可以用 `ensureArray` 方法简化。

2023-04-15 16:05 UTC, DreamOfIce commented on src/utils.ts
> +import type { CompilerOptions, Project } from 'ts-morph'
已修改

2023-04-15 16:05 UTC, DreamOfIce commented on src/utils.ts
> +export function getTsConfig(tsConfigPath: string, project: Project) {
已修改

2023-04-15 16:05 UTC, DreamOfIce commented on src/utils.ts
> +    const extendsConfigs = tsConfig.extends instanceof Array ? tsConfig.extends : [tsConfig.extends]
已修改

2023-04-16 02:27 UTC, DreamOfIce commented
另外，合并后能尽快release嘛，国内网络从git安装不太稳定

2023-04-16 13:40 UTC, qmhc requested changes
修改完后即可合并

2023-04-16 13:40 UTC, qmhc commented on src/utils.ts
> +export function getTsConfig(tsConfigPath: string, readFileSync: FileSystemHost['readFileSync']) {
我们应该将类型定义为通用的 readFile 类型：`(filePath: string, encoding?: string | undefined) => string`

2023-04-16 14:50 UTC, DreamOfIce commented on src/utils.ts
> +export function getTsConfig(tsConfigPath: string, readFileSync: FileSystemHost['readFileSync']) {
好了

2023-04-16 14:50 UTC, DreamOfIce commented
好了

2023-04-16 15:16 UTC, qmhc approved these changes

2023-04-16 17:30 UTC, DreamOfIce commented
可以合并了嘛（

2023-04-17 03:21 UTC, merged