feat: support only output dts
qmhc/vite-plugin-dts pull request #253
Opened 2023-07-27 08:41 UTC by biggerstar

过去输出dts同时会输出其他js产物
现在支持仅输出dts文件

2023-07-27 09:56 UTC, qmhc commented
是什么场景会使得：仅使用 vite 打包 dts，而用其他工具打包 js 代码？

2023-07-27 10:18 UTC, biggerstar commented
这是一个需求[vue-core](https://github.com/vuejs/core/blob/main/package.json#L21)
并非你说的 `仅使用 vite 打包 dts，而用其他工具打包 js 代码`
在某些情况下，可能在测试dts的时候我们只需要打包dts而不需要其他js产物   
而在我最近开发的一个工具中也有这种需求[vite-run](https://github.com/biggerstar/vite-run/blob/main/viterun.config.ts#L80)   
另外像一些大型仓库一般都有dts和源码分开打包的需求[vue-core-rollup.dts.config.js](https://github.com/vuejs/core/blob/main/rollup.dts.config.js#L28)
他们可以只在需要打包dts的自定义脚本中引入vite-plugin-dts就行

2023-07-27 10:23 UTC, biggerstar commented
上面说的`仅使用 vite 打包 dts，而用其他工具打包 js 代码`我还没回答清楚
这是回答:  `打包需求可以都使用vite， 只是可能有分开打包的需求`

2023-07-30 08:00 UTC, qmhc requested changes

2023-07-30 08:00 UTC, qmhc commented on src/types.ts
> +  onlyDts?: boolean,
请更名为 `declarationOnly`，并配上更详细的描述，特别要描述该选项会删除所有 vite 打包的原始产物，同时应添加默认值说明。

除此之外，还需要在两个 README 的选项文档中添加相应的内容。

2023-08-04 10:54 UTC, qmhc approved these changes

2023-08-04 10:54 UTC, merged